channels:
  - tidair-tag # pcas for rogue
  - lcls-ii
  - conda-forge
  - defaults
  - tidair-packages # pcas for rogue
dependencies:
  - python=3.7
  - psdaq
  - ami
  - ipywidgets
  - ipympl
  - jedi=0.17.2
  - caproto
  - scikit-image
  - scikit-beam
  - pytables
  - openmpi
  - mpi4py
  - rich
  - gdb
  - holoviews
  - panel
  - scikit-beam
  - seaborn
