channels:
  - lcls-ii
  - conda-forge
  - tidair-tag # pcas for rogue
  - tidair-packages # pcas for rogue
  - defaults
dependencies:
  - python=3.7
  #- psdaq
  - ami
  - ipywidgets
  - ipympl
  - jedi=0.17.2
  - caproto
  - scikit-image
  - scikit-beam
  - pytables
  - openmpi
  - mpi4py
  - rich
  - gdb
  - holoviews
  - panel
  - scikit-beam
  - seaborn
  - p4p
  - epics-base # make sure that the version matches the version of epicscorelibs
  - pyepics
  - xarray
