package:
  name: ami
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}

source:
  git_url: https://github.com/slac-lcls/ami.git

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - setuptools
    - python
    - pytest-runner
  run:
    - python
    - dill
    - pyzmq
    - pyqtgraph
    - networkfox
    - psana
    - ipython
    - pint
    - qtpy
    - asyncqt
    - amityping>=1.1.3
    - mypy
    - numba
    - h5py # optional: to use h5 source
    - pyarrow # optional: better pickling for arrays
    - scipy # optional: more algorithms
    - pytest-qt # optional: for test
    - pytest-asyncio # optional: for test
    - sympy
    - htop # optional: for memory leak debugging
    - setproctitle
