FROM centos:6

MAINTAINER Elliott Slaughter <slaughter@cs.stanford.edu>

ENV CONDA_PREFIX=/conda
ENV CONDA_ENV=myrel
ENV PATH=$CONDA_PREFIX/bin:$PATH

RUN yum -y install centos-release-scl && \
    yum -y install devtoolset-7 git wget && \
    yum clean all && \
    echo "source scl_source enable devtoolset-7" >> /etc/profile.d/enable-devtoolset-7.sh

ARG CONDA_ENV_FILE=env_create.yaml

ADD $CONDA_ENV_FILE .
ADD docker/make_conda_env.sh .

RUN ./make_conda_env.sh
