package:
  name: psdaq
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/slac-lcls/lcls2.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libibverbs') }}
    - {{ cdt('libibverbs-devel') }}
    - {{ cdt('libnl') }}
    - {{ cdt('librdmacm') }}
    - {{ cdt('librdmacm-devel') }}
    - {{ cdt('libudev') }}
    - {{ cdt('libudev-devel') }}
  host:
    - xtcdata
    - psalg
    - python
    - libfabric
    - epics-base >=7
    - prometheus-cpp
    - rapidjson
    - readline
    - zeromq=4.3.2 # workaround cmake file not found
    - p4p
    - zlib
    - libusdusb4
  run:
    - xtcdata
    - psalg
    - python
    - libfabric
    - rapidjson
    - readline
    - transitions
    - requests
    - zeromq=4.3.2 # workaround cmake file not found
    - prometheus_client
    - amityping
    - mypy
    - rogue>=v5.4.0 # sometimes it will revert to old version (because of arrow?)
    - bluesky
    - ophyd
    - p4p
    - lcls2_timetool
    - wave8
    - cameralink-gateway
    - epics-base >=7
    - zlib
    - libusdusb4
